server:
  port: ${SERVER_PORT}
  error:
    include-message: always

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

  datasource:
    url: jdbc:postgresql://localhost:5332/applog
    username: sidof
    password: sidof1/@
  driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          chartset: UTF
        smtp:
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          auth: true
          ssl:
            trust: "*"
          starttls:
            enable: true
    verify:
      host: ${VERIFY_EMAIL_HOST}

  servlet:
    multipart:
    max-file-size: 10MB
    max-request-size: 10MB
  main:
    web-application-type: servlet

project:
  image: images/
